#!/bin/bash
# Copyright 2018 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LC_ALL=C

set -eEuo pipefail
trap 'echo "Error: \`$BASH_COMMAND\` exited with status $?"' ERR

if (( EUID != 0 )); then
	echo 'This script must be run with root privileges.'
	exit 1
fi

# Setup cleanup trap to remove all temporary data.
cleanup() {
	echo '- Cleaning up.'
	[[ ${mount_dir:-} ]] && umount --recursive -- "$mount_dir"
	[[ ${loop_dev:-} ]] && losetup --detach "$loop_dev"
	[[ ${work_dir:-} ]] && rm -r -- "$work_dir"
	return 0
}
trap cleanup EXIT

echo '- Creating an empty raw disk image.'
work_dir=$(mktemp --directory --tmpdir="$PWD" build-arch-gce.XXX)
disk_raw=$work_dir/disk.raw
truncate --size=10G -- "$disk_raw"

echo '- Setting up a loop device and partitioning the image.'
loop_dev=$(losetup --find --partscan --show -- "$disk_raw")
sfdisk --quiet -- "$loop_dev" <<-'EOF'
	label:gpt
	type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B,size=300MiB,name=boot
	type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709,name=root
EOF

echo '- Formatting the root partition.'
root_dev=${loop_dev}p2
mkfs.ext4 -q -L root -- "$root_dev"
tune2fs -c 0 -i 0 -- "$root_dev"

echo '- Formatting the boot partition.'
boot_dev=${loop_dev}p1
mkfs.vfat -F32 -n BOOT -- "$boot_dev"

echo '- Mounting the root partition.'
mount_dir=$work_dir/disk.mnt
mkdir -- "$mount_dir"
mount -- "$root_dev" "$mount_dir"

echo '- Mounting the boot partition.'
mkdir -p -- "$mount_dir/boot"
mount -- "$boot_dev" "$mount_dir/boot"

echo '- Copy the host pacman database caches'
mkdir -p $mount_dir/var/lib/pacman/sync
rsync -r /var/lib/pacman/sync/ $mount_dir/var/lib/pacman/sync/

echo '- Installing Arch Linux.'
pacstrap -c -C "./sys/etc/pacman.conf" -- "$mount_dir" \
	base linux dosfstools e2fsprogs dhclient openssh sudo google-compute-engine \
	vim-minimal tmux mosh rsync unzip \
	google-cloud-ops-agent-git
cp -f ./sys/etc/pacman.conf "$mount_dir/etc/pacman.conf"

echo '- Configuring fstab.'
root_uuid=$(lsblk --noheadings --raw --output UUID -- "$root_dev")
boot_uuid=$(lsblk --noheadings --raw --output UUID -- "$boot_dev")
print_fstab() {
	printf '# LABEL=%s\n' "$1"
	printf 'UUID=%-20s' "$2"
	printf '\t%-10s' "$3" "$4" "$5"
	printf '\t%s %s' "$6" "$7"
	printf '\n\n'
} >> "$mount_dir/etc/fstab"
{
	print_fstab root "$root_uuid" / ext4 rw,discard,errors=remount-ro,x-systemd.growfs 0 1
	print_fstab boot "$boot_uuid" /boot vfat uid=root,gid=root,umask=022,showexec 0 0
}

echo '- Running additional setup in chroot.'

echo '-- Configuring systemd-repart.'

mkdir -p $mount_dir/etc/repart.d
cp -f ./sys/etc/repart.d/root.conf \
	$mount_dir/etc/repart.d/

mkdir -p $mount_dir/etc/systemd/system/systemd-repart.service.d
cp -f ./sys/etc/systemd/system/systemd-repart.service.d/override.conf \
	$mount_dir/etc/systemd/system/systemd-repart.service.d/

echo '-- Configuring NTP.'
mkdir -p $mount_dir/etc/systemd/timesyncd.conf.d/
cp ./sys/etc/systemd/timesyncd.conf.d/00-google.conf $mount_dir/etc/systemd/timesyncd.conf.d/

echo '-- Configuring locale.'
cp ./sys/etc/locale.gen $mount_dir/etc/locale.gen
cp ./sys/etc/locale.conf $mount_dir/etc/locale.conf

echo '-- Configuring journald.'
mkdir -p $mount_dir/etc/systemd/journald.conf.d
cp ./sys/etc/systemd/journald.conf.d/00-google.conf $mount_dir/etc/systemd/journald.conf.d/

## Disable password authentication and root login on SSH server.
echo '-- Configuring ssh.'
cp ./sys/etc/ssh/sshd_config $mount_dir/etc/ssh/

echo '-- Configuring pacman mirrorlist.'
cp -f ./sys/etc/pacman.d/mirrorlist $mount_dir/etc/pacman.d/mirrorlist

echo '-- Creating pacman-init service.'
cp ./sys/etc/systemd/system/pacman-init.service $mount_dir/etc/systemd/system/

echo '-- Configuring initcpio.'
cp ./sys/etc/mkinitcpio.conf $mount_dir/etc/
cp ./sys/etc/mkinitcpio.d/linux.preset $mount_dir/etc/mkinitcpio.d/

echo '-- Configuring Google Cloud Ops Agent.'
mkdir -p $mount_dir/etc/google-cloud-ops-agent/
cp ./sys/etc/google-cloud-ops-agent/config.yaml $mount_dir/etc/google-cloud-ops-agent/

arch-chroot -- "$mount_dir" /bin/bash -s <<-'EOS'
	set -eEuo pipefail
	trap 'echo "Error: \`$BASH_COMMAND\` exited with status $?"' ERR

	echo '-- Configuring time.'
	ln -sf /usr/share/zoneinfo/UTC /etc/localtime
	systemctl --quiet enable systemd-timesyncd.service

	echo '-- Running locale-gen.'
	locale-gen

	echo '-- Enabling sshd service.'
	systemctl --quiet enable sshd.service

	echo '-- Enabling pacman-init service.'
	systemctl --quiet enable pacman-init.service

	echo '-- Enabling google-cloud-ops-agent.service'
	systemctl --quiet enable google-cloud-ops-agent.service

	echo '-- Enabling other services.'
	systemctl --quiet enable dhclient@eth0.service

	echo '-- Running mkinitcpio.'
	rm /boot/initramfs-linux-fallback.img
	mkinitcpio --nocolor --preset linux

	echo '-- Running boot loader.'
	bootctl install --no-variables --quiet
EOS

echo '- Configuring boot loader.'
cp ./sys/efi/loader/loader.conf $mount_dir/boot/loader/
cp ./sys/efi/loader/entries/arch.conf $mount_dir/boot/loader/entries/

echo '- Configuring pacman hooks.'
mkdir -p -- "$mount_dir/etc/pacman.d/hooks"
cp ./sys/etc/pacman.d/hooks/00-systemd-boot.hook $mount_dir/etc/pacman.d/hooks/

echo '- Cleaning up and finalizing the image.'
> "$mount_dir/etc/machine-id"
rm -- "$mount_dir/var/log/pacman.log"
umount --recursive -- "$mount_dir"
unset mount_dir

echo '- Building the compressed image.'
disk_tar="arch-v$(date --utc +%Y%m%d).tar.gz"
tar --sparse -czf "$work_dir/$disk_tar" --directory="$work_dir" disk.raw
mv -- "$work_dir/$disk_tar" .

echo "Successfully built image \`$disk_tar\`."
